[package]
name = "pushin_boxes"
version = "0.1.0"
authors = ["Orlando Valverde <orlando.jesig.va@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[features]
default = ['bevy/dynamic']

[dependencies]
bevy_asset_ron = "0.4.0"
serde = "1.0.139"
ron = "0.7.1"

[dependencies.bevy-rust-arcade]
git = "https://github.com/rust-arcade/bevy-rust-arcade"

[dependencies.bevy]
version = "0.7.0"
default-features = false
features = ["bevy_winit", "render", "png"]

[dependencies.bevy_kira_audio]
version = "0.10.0"
default-features = false
features = ["wav"]

