[package]
name = "pushin_boxes"
version = "0.1.0"
authors = ["Orlando Valverde <orlando.jesig.va@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[features]
default = ['bevy/dynamic']

[dependencies]
bevy_asset_ron = "0.4.0"
serde = "1.0.136"
ron = "0.7.0"

[dependencies.hashbrown]
version = "0.12.0"
features = ["serde"]

[dependencies.bevy]
version = "0.7.0"
default-features = false
features = ["bevy_gilrs", "bevy_winit", "render", "png", "hdr", "x11", "filesystem_watcher"]

[dependencies.bevy_kira_audio]
version = "0.9.0"
features = ["wav"]

[dependencies.uuid]
version = "1.0.0"
features = ["v4", "fast-rng", "serde"]
