[package]
name = "pushin_boxes"
version = "0.1.0"
authors = ["Orlando Valverde <orlando.jesig.va@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[features]
default = ['bevy/dynamic']

[dependencies]
bevy_asset_ron = "0.3.1"
serde = "1.0.136"
ron = "0.7.0"

[dependencies.bevy]
version = "0.6.1"
default-features = false
features = ["bevy_gilrs", "bevy_winit", "render", "png", "hdr", "x11", "filesystem_watcher"]

[dependencies.bevy_kira_audio]
version = "0.8.0"
features = ["wav"]

